CREATE SCHEMA "calendar";

CREATE TABLE "calendar"."user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "created_at" timestamp DEFAULT
(now
())
);

CREATE TABLE "calendar"."meeting" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "from" timestamp,
  "to" timestamp,
  "created_at" timestamp DEFAULT
(now
())
);

CREATE TABLE "calendar"."schedule"
(
  "meeting_id" int,
  "user_id" int,
  PRIMARY KEY ("meeting_id", "user_id")
);

ALTER TABLE "calendar"."schedule" ADD FOREIGN KEY ("meeting_id") REFERENCES "calendar"."meeting" ("id");

ALTER TABLE "calendar"."schedule" ADD FOREIGN KEY ("user_id") REFERENCES "calendar"."user" ("id");
