WITH RankedHackers AS (
    SELECT 
        S1.SUBMISSION_DATE,
        S2.HACKER_ID,
        COUNT(S2.SUBMISSION_ID) AS SubmissionCount,
        ROW_NUMBER() OVER (PARTITION BY S1.SUBMISSION_DATE ORDER BY COUNT(S2.SUBMISSION_ID) DESC, S2.HACKER_ID) AS Rank
    FROM 
        SUBMISSIONS S1
    JOIN 
        SUBMISSIONS S2 ON S1.SUBMISSION_DATE = S2.SUBMISSION_DATE
    GROUP BY S1.SUBMISSION_DATE, S2.HACKER_ID
),
UniqueHackers AS (
    SELECT 
        S1.SUBMISSION_DATE,
        COUNT(DISTINCT S2.HACKER_ID) AS UniqueHackerCount
    FROM 
        SUBMISSIONS S1
    JOIN 
        SUBMISSIONS S2 ON S1.SUBMISSION_DATE = S2.SUBMISSION_DATE
    WHERE 
        (SELECT COUNT(DISTINCT S3.SUBMISSION_DATE)
         FROM SUBMISSIONS S3
         WHERE S3.HACKER_ID = S2.HACKER_ID AND S3.SUBMISSION_DATE < S1.SUBMISSION_DATE) 
        = DATEDIFF(DAY, '2016-03-01', S1.SUBMISSION_DATE)
    GROUP BY S1.SUBMISSION_DATE
),
FinalResult AS (
    SELECT 
        RH.SUBMISSION_DATE,
        UH.UniqueHackerCount,
        RH.HACKER_ID,
        H.NAME
    FROM 
        RankedHackers RH
    JOIN 
        UniqueHackers UH ON RH.SUBMISSION_DATE = UH.SUBMISSION_DATE
    JOIN 
        HACKERS H ON RH.HACKER_ID = H.HACKER_ID
    WHERE 
        RH.Rank = 1
)
SELECT 
    SUBMISSION_DATE,
    UniqueHackerCount,
    HACKER_ID,
    NAME
FROM 
    FinalResult
ORDER BY 
    SUBMISSION_DATE;
